### PR TITLE
Fix Json decoding

### PR DESCRIPTION
**Pull request by HannaTarasevich**
Fix https://github.com/WasiqB/multiple-cucumber-html-reporter/issues/316

### CODE REVIEW

**Comment by WasiqB** [comment]
Hi @HannaTarasevich , thanks for contributing to the project.

Please fix the failing test.

**Comment by HannaTarasevich** [comment]
Hi @WasiqB ,
Fixed

**Review by WasiqB — APPROVED** [review]

**Comment by HannaTarasevich** [comment]
Thanks @WasiqB!
Could we please release these update?

**Comment by WasiqB** [comment]
Sure @HannaTarasevich , once I reach home I will release this change

**Comment by ymouhat** [comment]
Hi @WasiqB 
after updating with version 3.6.2 I got the following result in show-info 

image

@cucumber/cucumber": "^10.0.0"
multiple-cucumber-html-reporter": "^3.6.2"
nodejs: 20.12.0
pnpm: 8.15.6
Platform : ubuntu

is this fix is supposed to fix that problem too? 
THank you in advance.

**Comment by HannaTarasevich** [comment]
Hi @ymouhat,
The fix is about JSON-attachment only.

By the way, @cucumber/cucumber v10 use string literals to attach all the data to json-report now (https://github.com/cucumber/cucumber-js/issues/2260), previously it was encoded. Your data is displayed as encoded, so I'd recommend to debug locally if your JSON-files with reports still contain encoded data.

**Comment by ymouhat** [comment]
HI @HannaTarasevich  Thank you for your reply.

**Comment by pls-spyro** [comment]
Hi, I have the same issue as @ymouhat - I have to stick to the 3.6.0 version in my reports because of that...

**Comment by ymouhat** [comment]
Hi @pls-spyro 
if it can help. 
for now we stayed in version 3.5.0 .
The developer indicated the problem seems to be due to a dependency with wdio-cucumberjs-json-reporter .  we are currently migrating to wdio8 we should give us the possibility to upgrade wdio-cucumberjs-json-reporter as well as multiple-cucumber-html-reporter to 3.6.2

**Comment by v-mwalk** [comment]
Just FYI - I hit this issue big time after moving to CucumberJS 10.8.0.

The test framework we use is Playwright/Cucumber based with multiple-cucumber-html-reporter being used to make results look pretty and usable.  However, as happened to Hanna, it meant all the text logging showed as base64 uck and screenshots/video (video was being attached as text/html within hand-rolled <video> tag) in double (as we base-64 encode the data as well) encoding!

However, updating to 3.6.2 mchr fixes all this nicely - thanks Hanna/Wasiq.  But note, only take 3.6.2 IF using attachments and moving to Cucumber v10+.

**Pull request merged**
